### ISSUE TITLE
What's the proper way to init ClsModule for E2E testing

### ISSUE THREAD

**Issue by pvogel1967** [Papooch/nestjs-cls#195]
We run e2e tests using jest and SuperTest.  We set up our app as follows:

```
        this._module = await Test.createTestingModule({
            imports: [AppModule, MetricsModule],
        }).compile();
        this._app = this._module.createNestApplication<NestExpressApplication>({
            ...this._appOptions,
            ...getAppOptions(),
        });
        await configureApp({
            app: this._app,
            skipSwagger: false,
            skipGzip: true,
        });
        if (initialStart) {
            this._contextId = this._mockContextIdFactoryMethods();
        }
        await this._app.init();
        this._app.enableShutdownHooks();
        await this._app.startAllMicroservices();
```

AppModule sets up CLS:
```   
 imports: [
        ClsModule.forRoot({
            global: true,
            middleware: { mount: true },
        }),
       ...
```

This works great up through nestjs-cls 4.0.1.  4.0.2 dies:

```
    Error initializing TestHarness Error: Cannot create ClsService because no AsyncLocalStorage instance was provided.
    Please make sure that ClsService is only provided by the ClsModule and not constructed manually or added to the providers array.
        at new ClsService (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/nestjs-cls/dist/src/lib/cls.service.js:34:19)
        at TestingInjector.instantiateClass (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:365:19)
        at callback (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:65:45)
        at TestingInjector.resolveConstructorParams (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:144:24)
        at TestingInjector.loadInstance (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:70:13)
        at TestingInjector.loadProvider (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:97:9)
        at /Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/instance-loader.js:56:13
```

What do we need to do to properly initialize CLS with an ALS for testing after 4.0.2?

**Comment by Papooch** [comment]
Hi, there should be no changes necessary when running E2E tests. Your setup looks correct.

However, the upgrade to [`4.0.2`](https://github.com/Papooch/nestjs-cls/releases/tag/nestjs-cls%404.0.2) might've exposed a bug in your application, where it was possible to accidentally put `ClsService` in your providers, which makes Nest create a "shell" instance without the correct `AsyncLocalStorage`.

The only correct way to get an instance of `ClsService` is through importing `ClsModule` or getting it statically through `ClsServiceManager.getClsService()`

Please look through your modules and see if you didn't accidentally put `ClsService` into `providers` of some module.

**Comment by pvogel1967** [comment]
@Papooch The _only_ way our app gets a ClsService is through DI, we import the ClsModule in the AppModule and then all our services' constructors have a ClsService that gets injected for example:

```
    constructor(
        private readonly cls: ClsService,
        @RootLogger() private readonly rootLogger: Bunyan,
        private readonly cache: AppCache,
        private readonly dbLevelConfigService: HydrowDbLevelConfigService,
    ) {}
```

On the _off_ chance that something weird got done I searched for all instances of ClsService in the codebase, and they are all either imports or declarations like you see above or via provider factories like this:

```
export const requestInterceptorProvider: FactoryProvider = {
    provide: APP_INTERCEPTOR,
    scope: Scope.REQUEST,
    inject: [InjectorKeys.LOGGER, AppCache, ClsService, TraceService],
    useFactory: async (logger: Bunyan, cache: AppCache, cls: ClsService, traceService: TraceService) => {
        return new RequestTrackerInterceptor(logger, cache, cls, traceService);
    },
};
```

There's one unit test that calls ClsServiceManager.getClsService() but that's not relevant to the issue above.

**Comment by Papooch** [comment]
Thanks for the follow-up. You could try updating to the latest version of `nestjs-cls` to see if it goes away.

If it doesn't (as I suspect), I would try debugging the issue by putting a console.log (or a breakpoint) into the constructor of ClsService (the compiled JavaScript) and see where and when it gets called.

If everything is set up correctly, there should be exactly _one_ instance of ClsService in the entire app.

Is it possible that you use some other library that uses `nestjs-cls` as a peer dependency, but sets it up incorrectly?

Try running `npm ls -r nestjs-cls` (or your other packages manager's equivalent) to find out what depends on it.

**Comment by pvogel1967** [comment]
No peer dependency. and it's a problem all the way up through the latest.  That's actually how I discovered the problem, dependabot was suggesting an update and its build fails all tests.  So I did a binary search to find where the problem first occurred, which turned out to be 4.0.2 (we're using 4.0.1 :-) ).

The console.log does give a hint, but I'm still not clear on what's calling the constructor here...  I added the following to the ClsService constructor:
```
const error = new Error();
console.log('ClsService.constructor()', error.stack);
```
To see where the calls are coming from.  This first call appears to be because of the require-in-the-middle package which is used by @opentelemetry/instrumentation.

```
ClsService.constructor() Error
    at new ClsService (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/nestjs-cls/dist/src/lib/cls.service.js:33:23)
    at Object.<anonymous> (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/nestjs-cls/dist/src/lib/cls-service.globals.js:7:28)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Module.patchedRequire (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/require-in-the-middle/index.js:217:27)
    at Hook._require.Module.require (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/require-in-the-middle/index.js:142:27)
    at Module.patchedRequire (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/require-in-the-middle/index.js:217:27)

ClsService.constructor() Error
    at new ClsService (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/nestjs-cls/dist/src/lib/cls.service.js:33:23)
    at Injector.instantiateClass (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:65:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Injector.resolveConstructorParams (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 0)
    at async InstanceLoader.createInstancesOfProviders (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
    at async /Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/instance-loader.js:40:13
    at async Promise.all (index 31)
    at async InstanceLoader.createInstances (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/instance-loader.js:39:9)
    at async InstanceLoader.createInstancesOfDependencies (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/injector/instance-loader.js:22:13)
    at async /Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/nest-factory.js:108:17
    at async ExceptionsZone.asyncRun (/Users/pvogel/dev/hydrow/data-api-v2/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
```

**Comment by Papooch** [comment]
The first call is the one made by the `nestjs-cls` library. The second line in the stack strace shows the call is made from `cls-service.globals.js`, which is where the single static _global_ instance of `ClsService` is created. So this is the correct one.

The second invocation seems wrong - it's Nest itself trying to create an instance (`InstanceLoader.createInstancesOfProviders`). This leads me to believe, that `ClsService` _is_ indeed placed into `providers` of some module. Maybe `TestHarness` (from the original error), since I presume that it only fails during tests and not when you start the app normally.

You could also try to start the app with `DEBUG=*` env var to see a detailed log of all Nest's calls and hopefully you'll spot something.

I'm afraid this is as much as I can help you, unless I can see the actual code.

**Comment by pvogel1967** [comment]
It fails even running standalone without the test harness.  

ClsService is a _dependency_ of most providers but is not listed as a provider itself.  The two patterns above and the import of ClsService where it's referenced as a dependency of a provider: 

`import { ClsService } from 'nestjs-cls';`

Are literally the only instances of the string ClsService in the entire code base.  So it's either being injected as a dependency in a factory provider or as a parameter to a provider class constructor.

UPDATE: I think I found it.  It is _not_ in the `providers` of any module, but it _was_ listed as an `import` in a module rather than just getting found by virtue of the `ClsModule.forRoot` in the AppModule.

**Comment by pvogel1967** [comment]
YES!  The rogue `import` of `ClsService` was the problem.

**Comment by Papooch** [comment]
Glad you found it.

If it was listed in `imports`, then Nest would still try to instantiate it, thinking it's a module.

In your case it was harmless (it was a module with no providers), but still an incorrect use.

**Comment by Papooch** [comment]
Closing as solved
