### ISSUE TITLE
can not access to CLS in e2e test after the first sub-test

### ISSUE THREAD

**Issue by ianzone** [Papooch/nestjs-cls#60]
Log
```
Error: Cannot set the key "logTrace". No CLS context available, please make sure that a ClsMiddleware/Guard/Interceptor has set up the context, or wrap any calls that depend on CLS with "ClsService#run"
    at ClsService.set (/home/ian/templates/vite-nest/node_modules/.pnpm/nestjs-cls@3.2.1_77foi4w27ghy47yutmnzv7krjy/node_modules/nestjs-cls/dist/src/lib/cls.service.js:41:19)
    at MiddlewareHost.use (/src/middlewares/authentication/authentication.middleware.ts:26:18)
    at MiddlewareHost.use (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/middleware/utils.js:48:30)
    at /home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Holder.done (/home/ian/templates/vite-nest/node_modules/.pnpm/@fastify+middie@8.1.0/node_modules/@fastify/middie/engine.js:107:13)
    at Object.run (/home/ian/templates/vite-nest/node_modules/.pnpm/@fastify+middie@8.1.0/node_modules/@fastify/middie/engine.js:59:12)
```

To reproduce:
1. degit https://github.com/ianzone/vite-nest-fastify to-check
2. cd to-check
3. pnpm i
4. pnpm run test

**Comment by Papooch** [comment]
I'll have a look. But it might be related to this one: https://github.com/Papooch/nestjs-cls/issues/49
